algoritmo "FuncoesAritimeticas"
var
   A: Real
inicio
      //A <- Abs(-50) //Abs = valor absoluto
      //A <- Exp(9,5) //Exp = Exponencial
      //A <- RaizQ(81) //RaizQ = Raiz Quadrada
      //A <- Int(RaizQ(81)) //Utilizando só a parte inteira
      //A <- GraupRad(90) //Conversão de grau para radiano
      A <- Sen(GraupRad(90)) //Qual sera o Seno de (Conversão de grau para radiano)
      Escreva (A)
fimalgoritmo
